/*
* bizLeads
*
* Usage
*
* ezAjax.bizLeads.toggleBizLeadStatus(leadId)
*
*/

ezAjax.bizListings= 
{
	/*
	* toggleisPremium
	*
	* This functions creates the object ezAja.ajax which will be used to post the 
	* form to the server.
	* 
	* Receives bizId
	* Sends request 
	* Expects confirmation of biz marked as premium successfuly.
	* Alert user with reponse in case of error.
	* 
	*/

	toggleIsPremium: function(bizId)
	{
		isPremium = $('#is_premium-'+bizId).val();

		ezAjax.ajax
		( 
			'biz_listings',
			{
				biz_id: bizId,
				is_premium: isPremium == 1 ? '0':'1'
			},

			function(response)
			{
				if (response.error != 'OK')
				{
					$('#is_premium-'+bizId)[0].checked = ! $('#is_premium-'+bizId)[0].checked;
					$('#is_premium-'+bizId).val( isPremium );
					alert(response.error);
				}
				else
				{
					
					if ( isPremium == 0 )
					{
						alert('Please note when you select "Use Lead System"\nyou will be billed for all leads generated by that listing');
					}
					
					$('#is_premium-'+bizId).val( isPremium == 1? 0:1);
				}
			},
			false,
			false
		);
	}

};
